CREATE DATABASE AC_1
USE AC_1

CREATE TABLE tb_DEPARTAMENTO
(
		COD_DEPTO		SMALLINT		IDENTITY
	,	DEPTO			VARCHAR(50)		NOT NULL

		CONSTRAINT		tb_DEPARTAMENTO_COD_CEPTO	PRIMARY KEY(COD_DEPTO)
)

INSERT tb_DEPARTAMENTO
(DEPTO)
VALUES
('Desenvolvimento'), ('Design'), ('Marketing'), ('Financeiro'), ('Admnistrativo')


CREATE TABLE tb_CARGO
(
		COD_CARGO		SMALLINT		IDENTITY
	,	CARGO			VARCHAR(50)		NOT NULL
	,	SALARIO_INIC	MONEY			NOT NULL

		CONSTRAINT		tb_CARGO_COD_CARGO	PRIMARY KEY(COD_CARGO)

)

INSERT tb_CARGO
		(CARGO, SALARIO_INIC)
VALUES
		('Dev-Front', 15000.00)
	,	('Dev-Back', 20000.00)
	,	('Designer', 11000.00)
	,	('Gerente de contas', 23615.00)	
	,	('Analista de comunicação', 7000.00)


CREATE TABLE tb_EMPREGADO
(
		CODFUN				SMALLINT		IDENTITY
	,	NOME				VARCHAR(50)		NOT NULL
	,	NUM_DEPEND			SMALLINT		NOT NULL
	,	DATA_NASCIMENTO		DATE			NOT NULL
	,	COD_DEPTO			SMALLINT		NOT NULL
	,	COD_CARGO			SMALLINT		NOT NULL
	,	DATA_ADMISSAO		DATE			NOT NULL
	,	SALARIO				MONEY			NOT NULL
	,	PREMIO_MENSAL		MONEY			NOT NULL
	,	SINDICALIZADO		VARCHAR(3)		NOT NULL
	,	OBS					VARCHAR(50)		NULL
	,	FOTO				BINARY			NULL
	,	COD_SUPERVISOR		SMALLINT		NULL


		CONSTRAINT		PK_tb_EMPREGADO_CODFUN	PRIMARY KEY(CODFUN)
	,	CONSTRAINT		FK_tb_EMPREGADO_COD_DEPTO	FOREIGN KEY(COD_DEPTO) REFERENCES tb_DEPARTAMENTO(COD_DEPTO)
	,	CONSTRAINT		FK_tb_EMPREGADO_COD_CARGO	FOREIGN KEY(COD_CARGO) REFERENCES tb_CARGO(COD_CARGO)

)



INSERT tb_EMPREGADO
(NOME, NUM_DEPEND, DATA_NASCIMENTO, COD_DEPTO, COD_CARGO, DATA_ADMISSAO, SALARIO, PREMIO_MENSAL, SINDICALIZADO)
VALUES
		('Vitor Fraga', 0, '07-11-2000', 1, 1, '31-08-2021', 1200.00, 500.00, 'Nao')
	,	('Lionel Messi', 3, '13-10-1984', 2, 3, '07-07-2021', 600.00, 100.00, 'Sim')
	,	('Clara Maria', 1, '31-01-2002', 4, 4, '01-01-2020', 2000.00, 300.00, 'Sim')
	,	('Melina Borges', 0, '08-11-2097', 3, 5, '13-11-2019', 5000.00, 1100.00, 'Sim')
	,	('Jeff Kaplan', 1, '26-02-1987', 1, 2, '06-11-2002', 1600.00, 760.00, 'Sim')



CREATE TABLE tb_DEPENDENTE
(
		CODDEP			SMALLINT		IDENTITY
	,	CODFUN			SMALLINT		NOT NULL
	,	NOME			VARCHAR(50)		NOT NULL
	,	DATA_NASCIMENTO	DATE			NOT NULL

		CONSTRAINT		PK_tb_DEPENDENTE	PRIMARY KEY(CODDEP)
	,	CONSTRAINT		FK_tb_DEPENDENTE	FOREIGN KEY(CODFUN) REFERENCES tb_EMPREGADO(CODFUN)
)


INSERT tb_DEPENDENTE
(CODFUN, NOME, DATA_NASCIMENTO)
VALUES
		(2, 'Lionel Junior ', '03-12-2006')
	,	(2,	'Lionel Filho',	'05-06-2012')
	,	(2,	'Lionelzinho Primeiro',	'05-06-2002')



--SELECT * FROM tb_CARGO
--SELECT * FROM tb_DEPARTAMENTO
--SELECT * FROM tb_EMPREGADO
--SELECT * FROM tb_DEPENDENTE
